controller_manager:
  ros__parameters:
    update_rate: 100

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["wheel_front_left_joint", "wheel_rear_left_joint"]
    right_wheel_names: ["wheel_front_right_joint", "wheel_rear_right_joint"]

    wheel_radius: 0.06
    wheel_separation: 0.30

    publish_rate: 50
    use_stamped_vel: false
    enable_odom_tf: true
    cmd_vel_timeout: 0.5

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0

    joint_state_interface_name: joint_states
    command_interface_type: velocity

pid_gains:
  wheel_front_left_joint:
    p: 8.0
    i: 0.0
    d: 0.05
    i_clamp: 1.0
  wheel_rear_left_joint:
    p: 8.0
    i: 0.0
    d: 0.05
    i_clamp: 1.0
  wheel_front_right_joint:
    p: 8.0
    i: 0.0
    d: 0.05
    i_clamp: 1.0
  wheel_rear_right_joint:
    p: 8.0
    i: 0.0
    d: 0.05
    i_clamp: 1.0